runtime:
  distribution_strategy: 'one_device'
  mixed_precision_dtype: 'float16'
  num_gpus: 1
task:
  train_data:
    global_batch_size: 8
    dtype: 'float16'
  validation_data:
    global_batch_size: 2
    dtype: 'float16'
