#!/usr/bin/env bash

output_dir="output"
[[ ! -d $output_dir ]] && mkdir -p $output_dir

export PYTHONPATH="/nas/loctx/tf-models:${PYTHONPATH}"
/usr/bin/env python3 train.py \
    --experiment=maskrcnn_resnetfpn_coco \
    --config_file=config.yaml \
    --mode=train \
    --model_dir=$output_dir
