#!/usr/bin/env bash

output_dir="output"
[[ ! -d $output_dir ]] && mkdir -p $output_dir

export PYTHONPATH="../..:${PYTHONPATH}"
/usr/bin/env python3 train.py \
    --experiment=yolo_darknet \
    --config_file=yolov4_512.yaml \
    --mode=train \
    --model_dir=${output_dir} 2>&1 | tee ${output_dir}/train.log
